# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- checkout: self
  persistCredentials: 'true'
  clean: 'true'
#- task: Docker@0
#  displayName: 'Run Jekyll'
#  inputs:
#    containerRegistryType: 'Container Registry'
#    action: 'Run an image'
#    imageName: 'jekyll/builder:latest'
#    volumes: |
#      $(build.sourcesDirectory):/srv/jekyll
#      $(build.sourcesDirectory)/live:/srv/jekyll/_site
#    containerCommand: 'sh -x -c "bundle install -V ; JEKYLL_ENV=production jekyll build -V"'
#    detached: false
- bash: |
    git config --local user.name "autogen"
    git config --local user.email "autogen-noreply@no-reply.softwareag.com"
    set -x
    ls -ltr
    pwd 
    env
    ls -ltr ..
    COMMIT=$(git rev-parse HEAD)
    git checkout gh-pages
    ls -ltr
    ls -ltr live
    date > akom.was.here
    git add akom.was.here
    git status
    git commit -m "Autogenerated site push from ${COMMIT}"
    git push
- bash: |
    git config --local user.name "autogen"
    git config --local user.email "autogen-noreply@no-reply.softwareag.com"
    set -x
    ls -ltr
    pwd 
    env
    ls -ltr ..
    COMMIT=$(git rev-parse HEAD)
    git checkout gh-pages
    ls -ltr
    ls -ltr live
    git add -A live
    git status
    git commit -m "Autogenerated site push from ${COMMIT}"
    git push
  displayName: 'Publish'
